# Next.js docker compose file for development

version: "3.7"

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development

# Usage
# docker-compose up --build
